[project]
name = "buffer-rollup"
authors = ["Core Dev Team"]
description = "Decentralized buffer management and versioning system"
telemetry = false
requirements = []
[contracts.buffer-core]
path = "contracts/buffer-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
